## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: check flake
  run: 'make check-flake'
  change: '*.nix'

- name: check default
  run: 'make check-default'
  change: '*.nix'
