## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

# Conditional task
- name: stage files to git
  run_on_init: true
  run: 
    - git add {{relative_filepath}}
    - git add -p
  change: 
    - '.fzz/on_success.evt'
    - '*.nix'
    - '.watch.yaml'
    - 'Makefile'
    - 'README.md'

- name: check flake
  run_on_init: true
  run: 
    - 'nix flake check --show-trace'
    ## if fails touch file to trigger next task
    - 'make build-all || touch hash-generate.tsk'
  change: '*.nix'

- name: regenerate generate hashes
  run: 
    - rm -rf *.log
    - make build-ergo 2> ergo.log || nvim ergo.log
    - make build-fzz 2> fzz.log || nvim fzz.log
    - rm -rf *.log
  change: 'hash-generate.tsk'

- name: check default
  run: 'make check-default'
  change: '*.nix'

# - name: All checks pass
#   run: 'touch .fzz/on_success.evt'
#   change:
#     - '**/*'
#   ignore:
#     - '.fzz/**'
#     - '.git/**'

- name: rebase to git
  run_on_init: true
  run: 
    - git fetch --all
    - git rebase origin/main
  change: 
    - '.git/COMMIT_EDITMSG'
